services:
  directory-service:
    image: directory-service
    container_name: directory-service
    build:
      context: ./directory-service
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
  media-service:
    image: media-service
    container_name: media-service
    build:
      context: ./media-service
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080
